export const EVENT_OK: 'ok' | 'cancel' = 'ok'
export const EVENT_CANCEL: 'ok' | 'cancel' = 'cancel'
export const EVENT_SKILL = 'skill'
export const EVENT_JOB = 'job'
export const EVENT_EDUCATION = 'education'
